import { JournalEntry, ChartOfAccountWithChildren, AssetSummary, TrialBalanceEntry, IncomeStatement, BalanceSheet, CashFlow, CoaSummary } from "@/types";

// ── Dummy Journal Entries ──────────────────────────────────────────────────
export const dummyJournals: JournalEntry[] = [
	{
		id: 1,
		date: "2026-04-21T10:30:00Z",
		description: "Pembelian Perlengkapan Kantor",
		createdAt: "2026-04-21T10:30:00Z",
		updatedAt: "2026-04-21T10:30:00Z",
		lines: [
			{
				id: 1,
				journalEntryId: 1,
				accountId: 6,
				debit: 500000,
				credit: 0,
				account: {
					id: 6,
					code: "5.01.01.04",
					name: "Biaya Perlengkapan",
					type: "EXPENSE",
					isPosting: true,
					parentId: 5,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 2,
				journalEntryId: 1,
				accountId: 1,
				debit: 0,
				credit: 500000,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 2,
		date: "2026-04-21T09:15:00Z",
		description: "Penerimaan Pendapatan Jasa",
		createdAt: "2026-04-21T09:15:00Z",
		updatedAt: "2026-04-21T09:15:00Z",
		lines: [
			{
				id: 3,
				journalEntryId: 2,
				accountId: 1,
				debit: 2000000,
				credit: 0,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 4,
				journalEntryId: 2,
				accountId: 7,
				debit: 0,
				credit: 2000000,
				account: {
					id: 7,
					code: "4.01.01.01",
					name: "Pendapatan Jasa",
					type: "REVENUE",
					isPosting: true,
					parentId: 6,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 3,
		date: "2026-04-20T14:22:00Z",
		description: "Pembayaran Hutang Supplier",
		createdAt: "2026-04-20T14:22:00Z",
		updatedAt: "2026-04-20T14:22:00Z",
		lines: [
			{
				id: 5,
				journalEntryId: 3,
				accountId: 8,
				debit: 1200000,
				credit: 0,
				account: {
					id: 8,
					code: "2.01.01.00",
					name: "Hutang Dagang",
					type: "LIABILITY",
					isPosting: true,
					parentId: 7,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 6,
				journalEntryId: 3,
				accountId: 2,
				debit: 0,
				credit: 1200000,
				account: {
					id: 2,
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: 2,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 4,
		date: "2026-04-20T11:00:00Z",
		description: "Gaji + Bonus Karyawan",
		createdAt: "2026-04-20T11:00:00Z",
		updatedAt: "2026-04-20T11:00:00Z",
		lines: [
			{
				id: 7,
				journalEntryId: 4,
				accountId: 9,
				debit: 4000000,
				credit: 0,
				account: {
					id: 9,
					code: "5.04.01.01",
					name: "Beban Gaji",
					type: "EXPENSE",
					isPosting: true,
					parentId: 8,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 8,
				journalEntryId: 4,
				accountId: 10,
				debit: 1000000,
				credit: 0,
				account: {
					id: 10,
					code: "5.04.01.02",
					name: "Beban Bonus",
					type: "EXPENSE",
					isPosting: true,
					parentId: 8,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 9,
				journalEntryId: 4,
				accountId: 1,
				debit: 0,
				credit: 5000000,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 5,
		date: "2026-04-19T08:00:00Z",
		description: "Setoran Modal Awal",
		createdAt: "2026-04-19T08:00:00Z",
		updatedAt: "2026-04-19T08:00:00Z",
		lines: [
			{
				id: 10,
				journalEntryId: 5,
				accountId: 2,
				debit: 50000000,
				credit: 0,
				account: {
					id: 2,
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: 2,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 11,
				journalEntryId: 5,
				accountId: 11,
				debit: 0,
				credit: 50000000,
				account: {
					id: 11,
					code: "3.00.00.00",
					name: "Modal",
					type: "EQUITY",
					isPosting: false,
					parentId: null,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	// Add more dummy entries here if needed
	{
		id: 6,
		date: "2026-04-21T10:30:00Z",
		description: "Pembelian Perlengkapan Kantor",
		createdAt: "2026-04-21T10:30:00Z",
		updatedAt: "2026-04-21T10:30:00Z",
		lines: [
			{
				id: 1,
				journalEntryId: 1,
				accountId: 6,
				debit: 500000,
				credit: 0,
				account: {
					id: 6,
					code: "5.01.01.04",
					name: "Biaya Perlengkapan",
					type: "EXPENSE",
					isPosting: true,
					parentId: 5,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 2,
				journalEntryId: 1,
				accountId: 1,
				debit: 0,
				credit: 500000,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 7,
		date: "2026-04-21T09:15:00Z",
		description: "Penerimaan Pendapatan Jasa",
		createdAt: "2026-04-21T09:15:00Z",
		updatedAt: "2026-04-21T09:15:00Z",
		lines: [
			{
				id: 3,
				journalEntryId: 2,
				accountId: 1,
				debit: 2000000,
				credit: 0,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 4,
				journalEntryId: 2,
				accountId: 7,
				debit: 0,
				credit: 2000000,
				account: {
					id: 7,
					code: "4.01.01.01",
					name: "Pendapatan Jasa",
					type: "REVENUE",
					isPosting: true,
					parentId: 6,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 8,
		date: "2026-04-20T14:22:00Z",
		description: "Pembayaran Hutang Supplier",
		createdAt: "2026-04-20T14:22:00Z",
		updatedAt: "2026-04-20T14:22:00Z",
		lines: [
			{
				id: 5,
				journalEntryId: 3,
				accountId: 8,
				debit: 1200000,
				credit: 0,
				account: {
					id: 8,
					code: "2.01.01.00",
					name: "Hutang Dagang",
					type: "LIABILITY",
					isPosting: true,
					parentId: 7,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 6,
				journalEntryId: 3,
				accountId: 2,
				debit: 0,
				credit: 1200000,
				account: {
					id: 2,
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: 2,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 9,
		date: "2026-04-20T11:00:00Z",
		description: "Gaji + Bonus Karyawan",
		createdAt: "2026-04-20T11:00:00Z",
		updatedAt: "2026-04-20T11:00:00Z",
		lines: [
			{
				id: 7,
				journalEntryId: 4,
				accountId: 9,
				debit: 4000000,
				credit: 0,
				account: {
					id: 9,
					code: "5.04.01.01",
					name: "Beban Gaji",
					type: "EXPENSE",
					isPosting: true,
					parentId: 8,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 8,
				journalEntryId: 4,
				accountId: 10,
				debit: 1000000,
				credit: 0,
				account: {
					id: 10,
					code: "5.04.01.02",
					name: "Beban Bonus",
					type: "EXPENSE",
					isPosting: true,
					parentId: 8,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 9,
				journalEntryId: 4,
				accountId: 1,
				debit: 0,
				credit: 5000000,
				account: {
					id: 1,
					code: "1.01.02.01",
					name: "Kas",
					type: "ASSET",
					isPosting: true,
					parentId: 1,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
	{
		id: 10,
		date: "2026-04-19T08:00:00Z",
		description: "Setoran Modal Awal",
		createdAt: "2026-04-19T08:00:00Z",
		updatedAt: "2026-04-19T08:00:00Z",
		lines: [
			{
				id: 10,
				journalEntryId: 5,
				accountId: 2,
				debit: 50000000,
				credit: 0,
				account: {
					id: 2,
					code: "1.01.01.02",
					name: "BCA - Main",
					type: "ASSET",
					isPosting: true,
					parentId: 2,
					createdAt: "",
					updatedAt: "",
				},
			},
			{
				id: 11,
				journalEntryId: 5,
				accountId: 11,
				debit: 0,
				credit: 50000000,
				account: {
					id: 11,
					code: "3.00.00.00",
					name: "Modal",
					type: "EQUITY",
					isPosting: false,
					parentId: null,
					createdAt: "",
					updatedAt: "",
				},
			},
		],
	},
];

// ── Dummy COA Tree (Asset only, berkepala 1) ───────────────────────────────
export const dummyAssetTree: ChartOfAccountWithChildren[] = [
	{
		id: 1,
		code: "1.01.00.00",
		name: "Aset Lancar",
		type: "ASSET",
		isPosting: false,
		parentId: null,
		createdAt: "",
		updatedAt: "",
		children: [
			{
				id: 2,
				code: "1.01.01.00",
				name: "Bank",
				type: "ASSET",
				isPosting: false,
				parentId: 1,
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: 1,
						code: "1.01.01.01",
						name: "Mandiri - Main",
						type: "ASSET",
						isPosting: true,
						parentId: 2,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: 2,
						code: "1.01.01.02",
						name: "BCA - Main",
						type: "ASSET",
						isPosting: true,
						parentId: 2,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: 3,
						code: "1.01.01.03",
						name: "Jago - Budget",
						type: "ASSET",
						isPosting: true,
						parentId: 2,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: 3,
				code: "1.01.02.00",
				name: "Kas",
				type: "ASSET",
				isPosting: false,
				parentId: 1,
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: 4,
						code: "1.01.02.01",
						name: "Wallet Cash",
						type: "ASSET",
						isPosting: true,
						parentId: 3,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: 4,
				code: "1.01.03.00",
				name: "E-Wallet",
				type: "ASSET",
				isPosting: false,
				parentId: 1,
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: 5,
						code: "1.01.03.01",
						name: "Gopay",
						type: "ASSET",
						isPosting: true,
						parentId: 4,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: 6,
						code: "1.01.03.02",
						name: "Dana",
						type: "ASSET",
						isPosting: true,
						parentId: 4,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
		],
	},
	{
		id: 5,
		code: "1.02.00.00",
		name: "Aset Non-Lancar",
		type: "ASSET",
		isPosting: false,
		parentId: null,
		createdAt: "",
		updatedAt: "",
		children: [
			{
				id: 6,
				code: "1.02.01.00",
				name: "Brokerage Accounts",
				type: "ASSET",
				isPosting: false,
				parentId: 5,
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: 7,
						code: "1.02.01.01",
						name: "Stockbit Sekuritas",
						type: "ASSET",
						isPosting: true,
						parentId: 6,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: 8,
						code: "1.02.01.02",
						name: "Pluang Sekuritas",
						type: "ASSET",
						isPosting: true,
						parentId: 6,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
			{
				id: 7,
				code: "1.02.05.00",
				name: "Saving & Commodities",
				type: "ASSET",
				isPosting: false,
				parentId: 5,
				createdAt: "",
				updatedAt: "",
				children: [
					{
						id: 9,
						code: "1.02.05.01",
						name: "Gold",
						type: "ASSET",
						isPosting: true,
						parentId: 7,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
					{
						id: 10,
						code: "1.02.05.03",
						name: "Emergency Fund",
						type: "ASSET",
						isPosting: true,
						parentId: 7,
						createdAt: "",
						updatedAt: "",
						children: [],
					},
				],
			},
		],
	},
];

// ── Dummy balance per account (DR - CR) ───────────────────────────────────
export const dummyBalances: Record<string, number> = {
	a1: 49100000, // Mandiri
	a2: 50000000, // BCA
	a3: 3000000, // Jago
	a4: 2500000, // Wallet Cash
	a5: 800000, // Gopay
	a6: 350000, // Dana
	a7: 12000000, // Stockbit
	a8: 5000000, // Pluang
	a9: 8500000, // Gold
	a10: 15000000, // Emergency Fund
};

// ── Dummy Laporan data ────────────────────────────────────────────────────
export const dummyTrialBalance: TrialBalanceEntry[] = [
	{ code: "1101", name: "Kas", type: "ASSET", debit: 5500000, credit: 0 },
	{ code: "1102", name: "Bank BCA", type: "ASSET", debit: 8700000, credit: 0 },
	{ code: "1110", name: "Piutang Usaha", type: "ASSET", debit: 1000000, credit: 0 },
	{ code: "1201", name: "Peralatan", type: "ASSET", debit: 6000000, credit: 0 },
	{ code: "1209", name: "Akum. Penyusutan", type: "ASSET", debit: 0, credit: 1500000 },
	{ code: "2001", name: "Hutang Dagang", type: "LIABILITY", debit: 0, credit: 3000000 },
	{ code: "3001", name: "Modal", type: "EQUITY", debit: 0, credit: 13000000 },
	{ code: "4001", name: "Pendapatan Jasa", type: "REVENUE", debit: 0, credit: 6000000 },
	{ code: "6001", name: "Biaya Perlengkapan", type: "EXPENSE", debit: 500000, credit: 0 },
	{ code: "6002", name: "Beban Gaji", type: "EXPENSE", debit: 1500000, credit: 0 },
	{ code: "6003", name: "Beban Lain-lain", type: "EXPENSE", debit: 300000, credit: 0 },
];

export const dummyIncomeStatement: IncomeStatement = {
	revenues: [{ name: "Pendapatan Jasa", amount: 6000000 }],
	expenses: [
		{ name: "Biaya Perlengkapan", amount: 500000 },
		{ name: "Beban Gaji", amount: 1500000 },
		{ name: "Beban Lain-lain", amount: 300000 },
	],
	totalRevenue: 6000000,
	totalExpense: 2300000,
	netIncome: 3700000,
};

export const dummyBalanceSheet: BalanceSheet = {
	currentAssets: [
		{ name: "Kas", balance: 5500000 },
		{ name: "Bank BCA", balance: 8700000 },
		{ name: "Piutang Usaha", balance: 1000000 },
	],
	nonCurrentAssets: [
		{ name: "Peralatan", balance: 6000000 },
		{ name: "Akum. Penyusutan", balance: -1500000 },
	],
	liabilities: [{ name: "Hutang Dagang", balance: 3000000 }],
	equity: [
		{ name: "Modal", balance: 13000000 },
		{ name: "Laba Periode Ini", balance: 3700000 },
	],
	totalCurrentAssets: 15200000,
	totalNonCurrentAssets: 4500000,
	totalAssets: 19700000,
	totalLiabilities: 3000000,
	totalEquity: 16700000,
};

export const dummyCashFlow: CashFlow = {
	operating: {
		lines: [
			{ label: "Penerimaan dari pelanggan", amount: 6000000 },
			{ label: "Pembayaran beban operasi", amount: -2300000 },
			{ label: "Pembayaran hutang dagang", amount: -2500000 },
		],
		total: 1200000,
	},
	investing: {
		lines: [{ label: "Pembelian instrumen investasi", amount: -5000000 }],
		total: -5000000,
	},
	financing: {
		lines: [{ label: "Setoran modal", amount: 50000000 }],
		total: 50000000,
	},
	netCashFlow: 46200000,
};

// ── Dummy Asset Summary ─────────────────────────────────────────────────────
export const dummyAssetSummary: AssetSummary = {
	totalAsset: 28500000,
	currentAsset: 18200000,
	groups: [
		{
			id: "g1",
			code: "1100",
			name: "Aset Lancar",
			icon: "wallet",
			totalBalance: 18200000,
			accounts: [
				{ id: 1, code: "1101", name: "Kas", balance: 5500000, isPosting: true },
				{ id: 2, code: "1102", name: "Bank BCA", balance: 8700000, isPosting: true },
				{ id: 3, code: "1103", name: "Bank Mandiri", balance: 3000000, isPosting: true },
				{ id: 4, code: "1110", name: "Piutang Usaha", balance: 1000000, isPosting: true },
			],
		},
		{
			id: "g2",
			code: "1200",
			name: "Aset Tetap",
			icon: "building",
			totalBalance: 9500000,
			accounts: [
				{ id: 5, code: "1201", name: "Peralatan Kantor", balance: 6000000, isPosting: true },
				{ id: 6, code: "1202", name: "Kendaraan", balance: 5000000, isPosting: true },
				{ id: 7, code: "1209", name: "Akum. Penyusutan", balance: -1500000, isPosting: true },
			],
		},
		{
			id: "g3",
			code: "1300",
			name: "Aset Lain-lain",
			icon: "clock",
			totalBalance: 800000,
			accounts: [
				{ id: 8, code: "1301", name: "Uang Muka", balance: 500000, isPosting: true },
				{ id: 9, code: "1302", name: "Biaya Dibayar Dimuka", balance: 300000, isPosting: true },
			],
		},
		{
			id: "g4",
			code: "1050",
			name: "Persediaan",
			icon: "package",
			totalBalance: 0,
			accounts: [],
		},
	],
};

// ── Dummy Full COA Tree ─────────────────────────────────────────────────────
export const dummyFullCoa: CoaSummary = {
	totalAccounts: 24,
	postingAccounts: 18,
	headerAccounts: 6,
	groups: [
		{
			type: "ASSET",
			label: "Aset",
			icon: "wallet",
			count: 12,
			accounts: [
				{
					id: 1, code: "1000", name: "Aset", type: "ASSET", isPosting: false, parentId: null, createdAt: "", updatedAt: "",
					children: [
						{
							id: 2, code: "1100", name: "Aset Lancar", type: "ASSET", isPosting: false, parentId: 1, createdAt: "", updatedAt: "",
							children: [
								{ id: 1, code: "1101", name: "Kas", type: "ASSET", isPosting: true, parentId: 2, createdAt: "", updatedAt: "", children: [] },
								{ id: 2, code: "1102", name: "Bank BCA", type: "ASSET", isPosting: true, parentId: 2, createdAt: "", updatedAt: "", children: [] },
								{ id: 3, code: "1103", name: "Bank Mandiri", type: "ASSET", isPosting: true, parentId: 2, createdAt: "", updatedAt: "", children: [] },
								{ id: 4, code: "1110", name: "Piutang Usaha", type: "ASSET", isPosting: true, parentId: 2, createdAt: "", updatedAt: "", children: [] },
							],
						},
						{
							id: 3, code: "1200", name: "Aset Tetap", type: "ASSET", isPosting: false, parentId: 1, createdAt: "", updatedAt: "",
							children: [
								{ id: 5, code: "1201", name: "Peralatan Kantor", type: "ASSET", isPosting: true, parentId: 3, createdAt: "", updatedAt: "", children: [] },
								{ id: 6, code: "1202", name: "Kendaraan", type: "ASSET", isPosting: true, parentId: 3, createdAt: "", updatedAt: "", children: [] },
								{ id: 7, code: "1209", name: "Akum. Penyusutan", type: "ASSET", isPosting: true, parentId: 3, createdAt: "", updatedAt: "", children: [] },
							],
						},
						{
							id: 4, code: "1300", name: "Aset Lain-lain", type: "ASSET", isPosting: false, parentId: 1, createdAt: "", updatedAt: "",
							children: [
								{ id: 8, code: "1301", name: "Uang Muka", type: "ASSET", isPosting: true, parentId: 4, createdAt: "", updatedAt: "", children: [] },
								{ id: 9, code: "1302", name: "Biaya Dibayar Dimuka", type: "ASSET", isPosting: true, parentId: 4, createdAt: "", updatedAt: "", children: [] },
							],
						},
					],
				},
			],
		},
		{
			type: "LIABILITY",
			label: "Liabilitas",
			icon: "credit-card",
			count: 4,
			accounts: [
				{
					id: 5, code: "2000", name: "Liabilitas", type: "LIABILITY", isPosting: false, parentId: null, createdAt: "", updatedAt: "",
					children: [
						{
							id: 6, code: "2100", name: "Liabilitas Jangka Pendek", type: "LIABILITY", isPosting: false, parentId: 5, createdAt: "", updatedAt: "",
							children: [
								{ id: 10, code: "2101", name: "Hutang Dagang", type: "LIABILITY", isPosting: true, parentId: 6, createdAt: "", updatedAt: "", children: [] },
								{ id: 11, code: "2102", name: "Hutang Pajak", type: "LIABILITY", isPosting: true, parentId: 6, createdAt: "", updatedAt: "", children: [] },
							],
						},
						{
							id: 7, code: "2200", name: "Liabilitas Jangka Panjang", type: "LIABILITY", isPosting: false, parentId: 5, createdAt: "", updatedAt: "",
							children: [
								{ id: 12, code: "2201", name: "Hutang Bank", type: "LIABILITY", isPosting: true, parentId: 7, createdAt: "", updatedAt: "", children: [] },
							],
						},
					],
				},
			],
		},
		{
			type: "EQUITY",
			label: "Ekuitas",
			icon: "landmark",
			count: 3,
			accounts: [
				{
					id: 8, code: "3000", name: "Ekuitas", type: "EQUITY", isPosting: false, parentId: null, createdAt: "", updatedAt: "",
					children: [
						{ id: 13, code: "3001", name: "Modal", type: "EQUITY", isPosting: true, parentId: 8, createdAt: "", updatedAt: "", children: [] },
						{ id: 14, code: "3002", name: "Laba Ditahan", type: "EQUITY", isPosting: true, parentId: 8, createdAt: "", updatedAt: "", children: [] },
						{ id: 15, code: "3003", name: "Laba Berjalan", type: "EQUITY", isPosting: true, parentId: 8, createdAt: "", updatedAt: "", children: [] },
					],
				},
			],
		},
		{
			type: "REVENUE",
			label: "Pendapatan",
			icon: "trending-up",
			count: 3,
			accounts: [
				{
					id: 9, code: "4000", name: "Pendapatan", type: "REVENUE", isPosting: false, parentId: null, createdAt: "", updatedAt: "",
					children: [
						{ id: 16, code: "4001", name: "Pendapatan Jasa", type: "REVENUE", isPosting: true, parentId: 9, createdAt: "", updatedAt: "", children: [] },
						{ id: 17, code: "4002", name: "Pendapatan Produk", type: "REVENUE", isPosting: true, parentId: 9, createdAt: "", updatedAt: "", children: [] },
						{ id: 18, code: "4003", name: "Pendapatan Lain-lain", type: "REVENUE", isPosting: true, parentId: 9, createdAt: "", updatedAt: "", children: [] },
					],
				},
			],
		},
		{
			type: "EXPENSE",
			label: "Beban",
			icon: "trending-down",
			count: 5,
			accounts: [
				{
					id: 10, code: "5000", name: "Beban", type: "EXPENSE", isPosting: false, parentId: null, createdAt: "", updatedAt: "",
					children: [
						{ id: 19, code: "5001", name: "Beban Gaji", type: "EXPENSE", isPosting: true, parentId: 10, createdAt: "", updatedAt: "", children: [] },
						{ id: 20, code: "5002", name: "Beban Sewa", type: "EXPENSE", isPosting: true, parentId: 10, createdAt: "", updatedAt: "", children: [] },
						{ id: 21, code: "5003", name: "Beban Listrik", type: "EXPENSE", isPosting: true, parentId: 10, createdAt: "", updatedAt: "", children: [] },
						{ id: 22, code: "5004", name: "Beban ATK", type: "EXPENSE", isPosting: true, parentId: 10, createdAt: "", updatedAt: "", children: [] },
						{ id: 23, code: "5005", name: "Beban Lain-lain", type: "EXPENSE", isPosting: true, parentId: 10, createdAt: "", updatedAt: "", children: [] },
					],
				},
			],
		},
	],
};
